/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 * Source file: /home/hose/libs/libcanard/dsdl_compiler/uavcan/equipment/actuator/1013.SetLimits.uavcan
 */
#include "uavcan/equipment/actuator/SetLimits.h"
#include "canard.h"

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) >= max) ? max : (x) );
#endif

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief uavcan_equipment_actuator_SetLimits_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns new offset
  */
uint32_t uavcan_equipment_actuator_SetLimits_encode_internal(uavcan_equipment_actuator_SetLimits* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
#ifndef CANARD_USE_FLOAT16_CAST
    uint16_t tmp_float = 0;
#else
    CANARD_USE_FLOAT16_CAST tmp_float = 0;
#endif

    canardEncodeScalar(msg_buf, offset, 8, (void*)&source->actuator_id); // 255
    offset += 8;

    source->use_limits = CANARD_INTERNAL_SATURATE_UNSIGNED(source->use_limits, 1)
    canardEncodeScalar(msg_buf, offset, 1, (void*)&source->use_limits); // 1
    offset += 1;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->offset);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->offset;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->limit_max);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->limit_max;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->limit_min);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->limit_min;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;
    source->home_now = CANARD_INTERNAL_SATURATE_UNSIGNED(source->home_now, 1)
    canardEncodeScalar(msg_buf, offset, 1, (void*)&source->home_now); // 1
    offset += 1;

    return offset;
}

/**
  * @brief uavcan_equipment_actuator_SetLimits_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t uavcan_equipment_actuator_SetLimits_encode(uavcan_equipment_actuator_SetLimits* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = uavcan_equipment_actuator_SetLimits_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief uavcan_equipment_actuator_SetLimits_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     uavcan_equipment_actuator_SetLimits dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @retval new offset or ERROR value if < 0
  */
int32_t uavcan_equipment_actuator_SetLimits_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  uavcan_equipment_actuator_SetLimits* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset)
{
    int32_t ret = 0;
#ifndef CANARD_USE_FLOAT16_CAST
    uint16_t tmp_float = 0;
#else
    CANARD_USE_FLOAT16_CAST tmp_float = 0;
#endif

    ret = canardDecodeScalar(transfer, (uint32_t)offset, 8, false, (void*)&dest->actuator_id);
    if (ret != 8)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
    offset += 8;

    ret = canardDecodeScalar(transfer, (uint32_t)offset, 1, false, (void*)&dest->use_limits);
    if (ret != 1)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
    offset += 1;

    // float16 special handling
    ret = canardDecodeScalar(transfer, (uint32_t)offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->offset = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->offset = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, (uint32_t)offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->limit_max = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->limit_max = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, (uint32_t)offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->limit_min = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->limit_min = (float)tmp_float;
#endif
    offset += 16;

    ret = canardDecodeScalar(transfer, (uint32_t)offset, 1, false, (void*)&dest->home_now);
    if (ret != 1)
    {
        goto uavcan_equipment_actuator_SetLimits_error_exit;
    }
    offset += 1;
    return offset;

uavcan_equipment_actuator_SetLimits_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief uavcan_equipment_actuator_SetLimits_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     uavcan_equipment_actuator_SetLimits dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t uavcan_equipment_actuator_SetLimits_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  uavcan_equipment_actuator_SetLimits* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    // Clear the destination struct
    for (uint32_t c = 0; c < sizeof(uavcan_equipment_actuator_SetLimits); c++)
    {
        ((uint8_t*)dest)[c] = 0x00;
    }

    ret = uavcan_equipment_actuator_SetLimits_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset);

    return ret;
}
